### ISSUE TITLE
ImportError: No module named 'aggregator'

### ISSUE THREAD

**Issue by iefan** [Code-ReaQtor/latex2mathml#1]
when i install with pip or setup.py, i successd. but when import latex2mathml, then error:

ImportError: No module named 'aggregator'

please check this version for python3.4

**Comment by Code-ReaQtor** [comment]
Thank you for reporting. I will release a fix as soon as I can.

**Comment by Code-ReaQtor** [comment]
Hi @iefan 

Compatibility with Python 3 have been fixed in in version 1.1.1

Thanks!

P.S. Tested for python versions 2.7, 3.4, 3.5
