### ISSUE TITLE
Convert from example result in IndexError: list index out of range

### ISSUE THREAD

**Issue by DenisSalem** [Code-ReaQtor/latex2mathml#33]
Hello there, I have a file ([math.txt](https://github.com/Code-ReaQtor/latex2mathml/files/2469062/math.txt)) with the following content (from examples).

```A_{m,n} = 
 \begin{bmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
 \end{bmatrix}
```
The code below is trying to parse and convert the above but fail with __IndexError: list index out ouf range__

```python
#! /usr/bin/python3

import latex2mathml.converter

latex_input = open("math.txt","r").read().strip()
mathml_output = latex2mathml.converter.convert(latex_input)
print(mathml_output)
```

Is there something I'm doing the wrong way? I'm using version 2.5.2

**Comment by Code-ReaQtor** [comment]
Hi @DenisSalem 
I wasn't able to test this after I migrated the parser to TexSoup. Thanks for checking. I will begin fixing this.

**Comment by DenisSalem** [comment]
@Code-ReaQtor Thank you for the quick reply and your awesome work!

**Comment by Code-ReaQtor** [comment]
3932671c8c6569d98c4108b77f9ae49bad062b5d

**Comment by Code-ReaQtor** [comment]
Hi @DenisSalem 

Version 2.6.0 have been released. Kindly check.

**Comment by DenisSalem** [comment]
Thank you :D
