### ISSUE TITLE
Crash when converting systems of equations

### ISSUE THREAD

**Issue by itsmeichigo** [Code-ReaQtor/latex2mathml#4]
Hi, I've stumbled upon a crash when trying to convert systems of equations. For example, when I try to convert this formula: 
`\left\{ \begin{array} { l } { 3x - 5y + 4z = 0} \\ { x - y + 8z = 0} \\ { 2x - 6y + z = 0} \end{array} \right.`

I got the following error in my log:

> File "/usr/local/lib/python2.7/dist-packages/latex2mathml/converter.py", line 20, in convert
    _classify_subgroup(aggregate(latex), row)
  File "/usr/local/lib/python2.7/dist-packages/latex2mathml/converter.py", line 95, in _classify_subgroup
    _classify_subgroup(element, _row)
  File "/usr/local/lib/python2.7/dist-packages/latex2mathml/converter.py", line 97, in _classify_subgroup
    _convert_command(element, elements, i, iterable, row)
  File "/usr/local/lib/python2.7/dist-packages/latex2mathml/converter.py", line 118, in _convert_command
    _convert_array_content(param, new_parent, alignment)
  File "/usr/local/lib/python2.7/dist-packages/latex2mathml/converter.py", line 70, in _convert_array_content
    __alignment = _alignment[index]
IndexError: list index out of range

Please see if you can fix this. Thanks for the library!
Ps: I'm using latest version 2.0.2.

**Comment by Code-ReaQtor** [comment]
@itsmeichigo 
I tried to validate the formula using [MathJax](https://www.mathjax.org/#demo) but I am only getting **_[Math Processing Error]_**

Kindly check the input.

**Comment by itsmeichigo** [comment]
Please make sure that you use the whole formula when validating (including the trailing `.` at the end). I tried with MathJax and it works. Please see the screenshot [here](https://imgur.com/a/gvpDWRm).

**Comment by Code-ReaQtor** [comment]
@itsmeichigo 

This is the `null delimeter`, right? It's not supported yet. Let me review it first.

**Comment by Code-ReaQtor** [comment]
Hi @itsmeichigo 

Please check the version 2.2.0 (latest)

Cheers! 🥂
