### ISSUE TITLE
Converting Formula returns weird values

### ISSUE THREAD

**Issue by Benjamin-T** [Code-ReaQtor/latex2mathml#5]
Dear @Code-ReaQtor,

When I try to parse a relatively straightforward formula:

$F_{x} = m \cdot a$

```python
from latex2mathml.converter import convert
convert("$F_{x} = m \cdot a$")
```
the following is returned:

```XML
b'<math>
    <mrow>
        <mi>$</mi>
        <msub>
            <mi>F</mi>
            <mrow>
                <mi>x</mi>
            </mrow>
        </msub>
        <mo>&amp;#x0003D;</mo>
        <mi>m</mi>
        <mo>&amp;#x022C5;</mo>
        <mi>a</mi>
        <mi>$</mi>
    </mrow>
</math>'
```

Why are \cdot and the '=' converted to '&amp;#x0003D;'  and '&amp;#x022C5;' ?? 

I'm using python 3.6.4 and running  the code in jupyter notebook. 

thanks in advance

**Comment by Code-ReaQtor** [comment]
Hi @Benjamin-T ,

Those are HTML entities (unicode) for the said characters. There is a current bug in cElementTree which "url-encodes" the ampersand. I haven't fixed this for a while (code is a year old). The generated MathML should be:

```xml
<math>
    <mrow>
        <mi>$</mi>
        <msub>
            <mi>F</mi>
            <mrow>
                <mi>x</mi>
            </mrow>
        </msub>
        <mo>&#x0003D;</mo>
        <mi>m</mi>
        <mo>&#x022C5;</mo>
        <mi>a</mi>
        <mi>$</mi>
    </mrow>
</math>
```

You should exclude the $ sign and try the following code as alternative:
```python
from latex2mathml.converter import convert
convert("F_{x} = m \cdot a").replace("&amp;", "&")
```

**Comment by Code-ReaQtor** [comment]
Hi @Benjamin-T 

latex2mathml 2.0.3 is out. Kindly upgrade, thanks.

```bash
pip install -U latex2mathml
```
